# Generated by Django 5.1.7 on 2025-05-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="response_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
